### ISSUE TITLE
CTRCryptoInputStream and other stream based classes should not get into subpackages

### ISSUE THREAD

**Issue by jerrychenhf** [intel-hadoop/chimera#101]
I am just astonished to find out that we have moved several very important classes
CryptoInputStream
CryptoOutputStream
CTRCryptoInputStream
CTRCryptoOutputStream
...

were moved to input, output sub packages. I don't think this should happen. It should stay in stream package.

**Comment by sundapeng** [comment]
@jerrychenhf  Sorry for introducing the issue, I created https://github.com/intel-hadoop/chimera/issues/102 for fixing it, please help to review.
