### ISSUE TITLE
Can we suport CBC in Cipher layer in 1.0 release?

### ISSUE THREAD

**Issue by jerrychenhf** [intel-hadoop/chimera#14]
I am thinking that if the changes are not so much, can we add the support to Cipher in 1.0 release if it is simple based on current refactor?
We don't need to add stream support of CBC mode in 1.0 release.

**Comment by sundapeng** [comment]
Good suggestion @jerrychenhf , https://github.com/intel-hadoop/chimera/pull/15 is adding cipher support cbc.

**Comment by sundapeng** [comment]
Merged with #15
