### ISSUE TITLE
Remove generateSecureRandom from Cipher interface

### ISSUE THREAD

**Issue by jerrychenhf** [intel-hadoop/chimera#18]
Secure Random generation is a separate concepts with Cipher although it is related. One don't have to depend an Cipher instance to generate secure random bytes.

We should design a simple factory for SecureRadom instantiation and don't have to include generateSecureRandom in Cipher interface.

**Comment by sundapeng** [comment]
Hi @jerrychenhf , It's a good suggestion, the issue will be fix at https://github.com/intel-hadoop/chimera/pull/20

**Comment by sundapeng** [comment]
Close the issue since https://github.com/intel-hadoop/chimera/pull/20 is merged
