### ISSUE TITLE
Discusssion: do we need to design a explicit close method for Cipher

### ISSUE THREAD

**Issue by jerrychenhf** [intel-hadoop/chimera#19]
One practice for Java Object which holds native resources is to implement the finalize method to allow Java garbage collector to call for freeing the native resources. While finalize gives burden to GC and it may have a bad impact. 

We notice Cipher or secure Random implementations (OpensslCipher and OSSecureRandom) may implement finalize for the above purposes.

Another practice to avoid finalize is to explicit close or dispose method such as java io Stream objects or JDBC connections.  This gives a efficient way of resource cleanup and leave the responsibility to developer to call close method when finish using.

What's your ideas?

**Comment by vanzin** [comment]
Why not both? `close()` for the developer who's careful about resource usage, `finalize()` for the forgetful kind.

**Comment by jerrychenhf** [comment]
@vanzin Providing both close and finalize is a valid practice. Java FileInputStream for example, has
both close and finalize method. finalize method is used as the last effort to clean up the file handle if a careless developer doesn't call close.  
When I am thinking to provide and use close method, I actually want to avoid finalize method. The main reason for this thoughts is finalize method will/may have a negative impact the GC environment although we see this practice in FileInputStream. When an object have finalize method, a special GC process is involved, such as during GC the objects with finalize method are put into a queue and so on. 
Last year, an Intel team profiled some GC problem on HBase region server. The GC frequently takes too long and found out the problem was due to finalize method of FileInputStream. In the running of region server, it will open many (large number of) files using FileInputStream. Even if close method is called for each of these input streams, while because these stream objects have finalize method, GC still needs to take care of all the processes for calling the finalize method for all these objects. Thus causes GC frequently taking longer time. 

This is why I feel to avoid finalize if close method is used, other than both. I will try to check whether I still have the slides of that problem and send you for your information.

**Comment by jerrychenhf** [comment]
@vanzin There is JIRA fired describing this:
https://issues.apache.org/jira/browse/HDFS-8562

**Comment by sundapeng** [comment]
Hi @jerrychenhf @vanzin , https://github.com/intel-hadoop/chimera/pull/20 is the pull request for this issue, please feel free to let me know if you have any comment.

**Comment by jerrychenhf** [comment]
Currently, just as @vanzin suggested, let's provide close method and keep finalize method. 
While close method is a contract for the API developer and finalize method is implementation details. 

The finalize is possible to be removed if there are impact found.

**Comment by vanzin** [comment]
> finalize method will/may have a negative impact the GC environment 

Is the extra overhead of finalize because it exists, or because without a close, the finalize implementations needs to do work? My guess would be the second. With both close and finalize, objects that have been closed would pretty much have a no-op finalize, and GC should not be negatively affected.

**Comment by jerrychenhf** [comment]
@vanzin It is actually because the existence of finalize method. As long as an class override finalize and provide an implementation, GC will have do handle all the stuff to call finalize even if the close method is already called. Because calling of the close and reset some flag to indicate the object is closed is implementation details of the class and JVM GC has no way to know this.

**Comment by sundapeng** [comment]
Closed this ticket since https://github.com/intel-hadoop/chimera/pull/32 is merged. Thank @jerrychenhf       and @vanzin
