### ISSUE TITLE
Stop unnecessary buffer copy

### ISSUE THREAD

**Issue by winningsix** [intel-hadoop/chimera#3]
In CryptoInputStream.read(ByteBuffer), this is what happens:
  * read from input into user-provided buffer
  * copy from user provided buffer to inBuffer
  * decrypt content of inBuffer, write to outBuffer
  * copy from outBuffer to user buffer

The first copy seems unnecessary; can't you read directly into inBuffer?

It would be nice if the second copy were not needed, but it could be
that the user buffer doesn't have enough space for all the decrypted
data, so maybe there's no way around it...(Found by @vanzin)

**Comment by dianfu** [comment]
Thanks for reporting this issue.
For the elimate of the first copy, it's fixed in de040588a25c023b7b2a7208516f3e94a8d2d979.
For the elimate of the the second copy, it's fixed in 9813ce1ede0d6cbc2c05b7b99d7a1b0075565392.
