### ISSUE TITLE
0.9.1 Release

### ISSUE THREAD

**Issue by jerrychenhf** [intel-hadoop/chimera#49]
Hi folks,
Since the code is stable for some period of time now and we can consider a release now.
Since there is discussion and effort on going to make Chimera part of Apache, we suggest to name the next release as 0.9.1 instead of 1.0.

Thanks,
Haifeng

**Comment by winningsix** [comment]
+1 for the proposal.

**Comment by dianfu** [comment]
+1.

**Comment by sundapeng** [comment]
+1 for the proposal.

**Comment by winningsix** [comment]
Closed in branch [release 0.9.1](https://github.com/intel-hadoop/chimera/releases)
