### ISSUE TITLE
Refine and Implement tests for CryptoInputStream and CryptoOutputStream

### ISSUE THREAD

**Issue by jerrychenhf** [intel-hadoop/chimera#59]
The CryptoInputStream and CryptoOutputStream are new for support AES CBC/CTR/GCM and and all others.

We need to refine the existing test infrastructure to test these. Anybody take this task?

**Comment by sundapeng** [comment]
Good suggestion, I will working on it.

**Comment by jerrychenhf** [comment]
Thanks Dapeng for working on this!

**Comment by sundapeng** [comment]
close the ticket since https://github.com/intel-hadoop/chimera/pull/63 is merged
