### ISSUE TITLE
Reorganize the tests class

### ISSUE THREAD

**Issue by jerrychenhf** [intel-hadoop/chimera#65]
This current organize of the tests class is somewhat strange. for example, under package com.intel.chimera, we have several classes to test stream and there is new packge com.intel.chimera.stream.

Can we reorganize for easy to understanding the role of the test classes?

**Comment by sundapeng** [comment]
@jerrychenhf @winningsix , I will reorganize the tests class.

**Comment by sundapeng** [comment]
Close the issue since https://github.com/intel-hadoop/chimera/pull/69 merged
