### ISSUE TITLE
is readFully necessary for Input interface

### ISSUE THREAD

**Issue by jerrychenhf** [intel-hadoop/chimera#81]
I thinking that the positioned readFully can be implemented by read(position).
Is it OK to remove readFully from Input interface to simplify the interface definition and put readFully in the implementation of Utility or even in PositionedCryptoInputStream?

The implementation is as simple as this:

    int nread = 0;
    while (nread < length) {
      int nbytes = read(position+nread, buffer, offset+nread, length-nread);
      if (nbytes < 0) {
        throw new EOFException("End of file reached before reading fully.");
      }
      nread += nbytes;
    }

**Comment by colinmjj** [comment]
@jerrychenhf , I think it's reasonable. Currently, both ChannelInput and StreamInput don't support readFully. We should remove this to simplify the interface. I'll work on this.

**Comment by jerrychenhf** [comment]
Can other body makes comments, especially @dianfu ?
