### ISSUE TITLE
[DISCUSS]Reorganize the packages of input,output and stream?

### ISSUE THREAD

**Issue by sundapeng** [intel-hadoop/chimera#92]
Hi all,

Currently, `input` and `output` are the same levels with `cipher`,`stream`,`random`, package `input`(same as output) have the following classes: `Input`,`ChannelInput`and `StreamInput`, these classes are related to `stream` actually, I wonder if we can reorganize the packages to make it more clear. I have some proposed solutions for reorganizing the package, any other ideas are also welcomed:

(0) Should not change the package
(1) Putting all the classes (`input` and `output`) into `stream`
(2) Reorganizing according package `com.intel.chimera.stream.input` and package `com.intel.chimera.stream.output`

**Comment by jerrychenhf** [comment]
Strictly speaking, yeah, Input and Output are for stream. 
If we plan to do something on this, I like approach (2).

**Comment by jerrychenhf** [comment]
Anybody has other comments on this?

**Comment by jerrychenhf** [comment]
What's the plan for this?

**Comment by sundapeng** [comment]
Hi @jerrychenhf , I'm also agreed with `Reorganizing according package com.intel.chimera.stream.input and package com.intel.chimera.stream.output`, how about follow up a pull request about this.

**Comment by JkSelf** [comment]
Hi @jerrychenhf @sundapeng ,I have created a PR https://github.com/intel-hadoop/chimera/pull/98 for this issue.

**Comment by sundapeng** [comment]
Thanks @JkSelf for your contribution
