### ISSUE TITLE
[DISCUSS] ConfigurationKeys should be renamed to Configuration and CONSTANT?

### ISSUE THREAD

**Issue by sundapeng** [intel-hadoop/chimera#93]
`ConfigurationKeys` contains both configuration key and configuration value, it may need a better class name.

**Comment by jerrychenhf** [comment]
I found some similar cases like this in Hadoop. For example, DFSConfigKeys extends CommonConfigurationKeys and these classes contains both the keys and default values.

So we can keep as it was now.

**Comment by sundapeng** [comment]
SGTM, thank you for your comments.
